source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'RMPScrollingMenuBarController', :exclusive => true do
  pod "RMPScrollingMenuBarController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "RMPScrollingMenuBarController", :path => "../"

  pod 'FBSnapshotTestCase'
end
